version: '2.4'

services:
  mariadb:
    image: arm64v8/mariadb:10.5
    container_name: limesurvey-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: limesurvey
      MYSQL_USER: lsuser
      MYSQL_PASSWORD: lspass
    volumes:
      - /root/PROJECT/survey/db:/var/lib/mysql
    networks:
      - limesurvey-net
    mem_limit: 512m
    cpus: 1.0
  limesurvey:
    image: acspri/limesurvey:latest
    container_name: limesurvey-app
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - 8082:80
    environment:
      LIMESURVEY_DB_HOST: mariadb
      LIMESURVEY_DB_NAME: limesurvey
      LIMESURVEY_DB_USER: lsuser
      LIMESURVEY_DB_PASSWORD: lspass
      LIMESURVEY_ADMIN_USER: admin
      LIMESURVEY_ADMIN_PASSWORD: admin123
      LIMESURVEY_ADMIN_NAME: "Admin Survey"
      LIMESURVEY_ADMIN_EMAIL: masihgurutkj@gmail.com
    volumes:
      - /root/PROJECT/survey/app:/var/www/html/upload:rw
    networks:
      - limesurvey-net
    mem_limit: 512m
    cpus: 1.0
  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: limesurvey-phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      #PMA_USER: root
      #PMA_PASSWORD: toor
    networks:
      - limesurvey-net
    mem_limit: 128m
    cpus: 1.0

networks:
  limesurvey-net:
    driver: bridge
